apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking-experiment
spec:
  selector:
    app: booking-service
  ports:
  - port: 5002
    targetPort: 5002
  type: LoadBalancer
