apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
  namespace: booking-experiment
type: Opaque
stringData:
  POSTGRES_DB: inventory_db
  POSTGRES_USER: inventory_user
  POSTGRES_PASSWORD: inventory_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: booking-db-secret
  namespace: booking-experiment
type: Opaque
stringData:
  POSTGRES_DB: booking_db
  POSTGRES_USER: booking_user
  POSTGRES_PASSWORD: booking_pass
